### ISSUE TITLE
Consider populating the Viewport Size fields in the Vectorizer with that specified in `trainees.js`

### ISSUE THREAD

**Issue by biancadanforth** [mozilla/fathom-fox#36] opened 2019-06-28 04:19 UTC
The Vectorizer currently populates the dropdown with the features specified in `trainees.js`, but it does not populate the Viewport Size fields which are also specified in `trainees.js`. It'd be helpful if that were autopopulated as well.

**Comment by erikrose** [comment] 2019-06-28 17:46
Great minds think alike! Dupe of #32.

**Closed by erikrose** 2019-06-28 17:46 UTC
